import Link from "next/link";
import "../globals.css";

export const metadata = {
	title: "Chetan Arora",
	description: "Generated by Next + Sanity",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="mx-auto max-w-5xl py-10">
				<header className="mx-auto w-11/12">
					<Link
						className="bg-gradient-to-r from-amber-500 via-red-500 to-violet-500 bg-clip-text text-2xl font-bold text-transparent"
						href={"/"}
					>
						Chetan
					</Link>
				</header>
				<main className="mx-auto w-11/12 py-10">{children}</main>
			</body>
		</html>
	);
}
