import './globals.css'

export const metadata = {
  title: 'Chetan Arora',
  description: 'Generated by Next + Sanity',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-[90%] mx-auto'>{children}</body>
    </html>
  )
}
